/** Auto-generated by scripts/vendor-wechat.mjs — do not edit by hand. */
export const WEIXIN_PACKAGE_META = {
  name: "@tencent-weixin/openclaw-weixin",
  version: "2.4.9",
  ilink_appid: "bot",
} as const;
